### ISSUE TITLE
The execution of commands from the list does not work

### ISSUE THREAD

**Issue by archroot** [ZeTioZ/OpsyDistance#2]
Ignores the specified command in the execute section in the configuration and always returns the response [ZeDistance] Please, make sure you set the commands to execute in the configs file!

you lost the sign ! 

if(!config.getStringList("command.execute").isEmpty())
{

**Comment by ZeTioZ** [comment]
Gonna look at it ^^

**Comment by ZeTioZ** [comment]
Fixed in commit https://github.com/ZeTioZ/ZeDistance/commit/1ca585427fc1b57dcd5799206c514d150589b21d
